name: Release mosdns docker

on:
  push:
    paths:
      - "tag"
      - "Dockerfile"
      - ".github/workflows/release.yml"
  workflow_dispatch:

jobs:
  build-docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set env
        run: |
          echo "TAG=$(cat tag)" >> $GITHUB_ENV

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          build-args: |
            TAG=${{ env.TAG }}
            REPOSITORY=IrineSistiana/mosdns
          platforms: linux/amd64,linux/arm/v7,linux/arm64,linux/ppc64le
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/mosdns:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/mosdns:${{ env.TAG }}
